; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter, extra scripting
;   Upload options: custom port, speed and extra flags
;   Library options: dependencies, extra library storages
;
; Please visit documentation for the other options and examples
; http://docs.platformio.org/en/stable/projectconf.html

[platformio]
; Added this here to "hard code" the environment for macro debugging/visuals
;default_envs = esp32_wifi_tft


[env]
lib_compat_mode = off


[common]
framework = espidf
; The default platform & platform package only applies to ESP32 derivatives
platform = espressif32
lib_deps =
    bblanchon/ArduinoJson @ ^7.4.2
    https://github.com/thorrak/thorlog.git
    https://github.com/tzapu/WiFiManager.git#0d84861270c3cd64f72a4eaf34443ee580d2547e ; Anchor to latest commit as of 8/7/24
    bblanchon/StreamUtils @ ^1.9.1
    https://github.com/thorrak/esp32_ds18b20.git
lib_deps_bluetooth =
    ;h2zero/esp-nimble-cpp @ ^2.3.4 ; https://github.com/h2zero/NimBLE-Arduino.git
board_build.embed_txtfiles =
    managed_components/espressif__esp_insights/server_certs/https_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_mqtt_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_claim_service_server.crt
    managed_components/espressif__esp_rainmaker/server_certs/rmaker_ota_server.crt    

; Let's also include some other common build flags for ease-of-use
build_flags =
    !python3 scripts/gen_version.py
    -DCONFIG_USE_NATIVE_CPP_NEW
    -D CORE_DEBUG_LEVEL=0               ; Set core Arduino log level (5 = high)
    -D THORLOG_LOG_LEVEL=0              ; Set Serial log level (6 = high)
    -D CONFIG_NIMBLE_CPP_LOG_LEVEL=0    ; Set NimBLE log level (4 = high)
    -D DISABLE_LOGGING                  ; This will remove log lib from sketch

; Remove some espressif components we don't need to reduce build size (mostly for iram savings)
custom_sdkconfig = CONFIG_SPIRAM_CACHE_LIBTIME_IN_IRAM=n
                   CONFIG_ESP_HTTPS_SERVER_ENABLE=n
custom_component_remove = espressif/esp_hosted
                          espressif/esp_wifi_remote
                          espressif/esp_modem
                          espressif/esp-dsp
                          espressif/esp-zboss-lib
                          espressif/esp-zigbee-lib
                          espressif/esp_rainmaker
                          espressif/rmaker_common
                          espressif/esp_insights
                          espressif/esp_diag_data_store
                          espressif/esp_diagnostics
                          espressif/cbor
                          espressif/qrcode
                          espressif/esp-sr
                          espressif/libsodium
                          espressif/esp-modbus
                          espressif/esp32-camera

upload_speed = 460800
monitor_speed = 115200
; These are true for most devices on MacOS - Will likely need to be changed if compiling on other platforms
build_type = release
monitor_dtr = 1
monitor_rts = 1


[env:esp32_wifi_tft]
board = lolin_d32
platform = ${common.platform}
framework = ${common.framework}
; board_build.arduino.upstream_packages = no
; For esp32_wifi_tft we want to enable LCD support, TFT support, and WiFi support
build_flags =
    ${common.build_flags}
    -DBREWPI_LCD
    ; BREWPI_TFT is the flag we're using for TFTs in general
    ; BREWPI_TFT_ILI9341 is the flag we're using for the "big" (LoLin) TFTs
    -DBREWPI_TFT
    -DBREWPI_TFT_ILI9341
    -DCONNECT_VIA_WIFI
    -DHAS_BLUETOOTH
    -DEXTERN_SENSOR_ACTUATOR_SUPPORT
    ; -DENABLE_PROMETHEUS_SERVER
    -DENABLE_HTTP_INTERFACE
    -DESP32_STOCK
lib_deps =
    ${common.lib_deps}
    ${common.lib_deps_bluetooth}
    https://github.com/PaulStoffregen/XPT2046_Touchscreen
    adafruit/Adafruit GFX Library@^1.11.5
    adafruit/Adafruit ILI9341@^1.5.12
    adafruit/Adafruit BusIO@^1.14.1
upload_speed = ${common.upload_speed}
monitor_speed = ${common.monitor_speed}
board_build.embed_txtfiles = ${common.board_build.embed_txtfiles}
board_build.partitions = 4mb_no_ota.csv
board_build.filesystem = littlefs
build_type = ${common.build_type}
custom_sdkconfig = ${common.custom_sdkconfig}
custom_component_remove = ${common.custom_component_remove}
monitor_filters =
    esp32_exception_decoder


[env:esp32_wifi_iic]
board = lolin_d32
platform = ${common.platform}
framework = ${common.framework}
; For esp32_wifi_iic we want to enable LCD support, IIC support, and WiFi support
build_flags =
    ${common.build_flags}
    -DBREWPI_LCD
    -DBREWPI_IIC
    -DCONNECT_VIA_WIFI
    -DHAS_BLUETOOTH
    -DEXTERN_SENSOR_ACTUATOR_SUPPORT
    ; -DENABLE_PROMETHEUS_SERVER
    -DENABLE_HTTP_INTERFACE
    -DESP32_STOCK
lib_deps =
    ${common.lib_deps}
    ${common.lib_deps_bluetooth}
upload_speed = ${common.upload_speed}
monitor_speed = ${common.monitor_speed}
board_build.embed_txtfiles = ${common.board_build.embed_txtfiles}
board_build.partitions = 4mb_no_ota.csv
board_build.filesystem = littlefs
build_type = ${common.build_type}
custom_sdkconfig = ${common.custom_sdkconfig}
custom_component_remove = ${common.custom_component_remove}
monitor_filters =
    esp32_exception_decoder


; [env:esp32_c3_wifi]
; platform = espressif32
; board = lolin_c3_mini
; framework = ${common.framework}
; ; For esp32_c3_wifi we want to enable LCD support, TFT support, and WiFi support
; build_flags =
;     ${common.build_flags}
;     -DBREWPI_LCD
;     -DBREWPI_IIC
;     -DCONNECT_VIA_WIFI
;     -DEXTERN_SENSOR_ACTUATOR_SUPPORT
;     ; -DENABLE_PROMETHEUS_SERVER
;     ; -DENABLE_HTTP_INTERFACE
;     -DESP32C3
; lib_deps =
;     ${common.lib_deps}
; upload_speed = ${common.upload_speed}
; monitor_speed = ${common.monitor_speed}
; board_build.embed_txtfiles = ${common.board_build.embed_txtfiles}
; board_build.partitions = 4mb_inc_ota.csv
; ;board_build.filesystem = littlefs
; build_type = ${common.build_type}
; custom_component_remove = ${common.custom_component_remove}
; monitor_filters =
;     esp32_exception_decoder


[env:esp32_s2_wifi]
board = lolin_s2_mini
platform = ${common.platform}
framework = ${common.framework}
; v4.4.4 of esp-idf introduces a bug in the IIC implementation that causes MASSIVE delays
; in the IIC bus on the S2 (meaning that writes to the LCD grind the controller to a halt). 
; This appears to be related to https://github.com/espressif/arduino-esp32/issues/8480#issuecomment-1708909457
; For esp32_s2_wifi we want to enable LCD support, IIC support, and WiFi support
; There is no Bluetooth support on this chip. 
build_flags =
    ${common.build_flags}
    -DBREWPI_LCD
    -DBREWPI_IIC
    -DCONNECT_VIA_WIFI
    -DENABLE_HTTP_INTERFACE
    -DEXTERN_SENSOR_ACTUATOR_SUPPORT
    ; -DENABLE_PROMETHEUS_SERVER
    -DESP32S2
lib_deps =
    ${common.lib_deps}
upload_speed = ${common.upload_speed}
monitor_speed = ${common.monitor_speed}
board_build.embed_txtfiles = ${common.board_build.embed_txtfiles}
board_build.partitions = 4mb_inc_ota.csv
board_build.filesystem = littlefs
build_type = ${common.build_type}
custom_component_remove = ${common.custom_component_remove}
monitor_filters =
    esp32_exception_decoder


; [env:esp32_s2_serial]
; board = lolin_s2_mini
; platform = ${common.platform}
; framework = ${common.framework}
; ; v4.4.4 of esp-idf introduces a bug in the IIC implementation that causes MASSIVE delays
; ; in the IIC bus on the S2 (meaning that writes to the LCD grind the controller to a halt). 
; ; This appears to be related to https://github.com/espressif/arduino-esp32/issues/8480#issuecomment-1708909457
; ; For esp32_s2_serial we want to enable LCD support, IIC support, and Serial support
; ; There is no Bluetooth support on this chip. 
; build_flags =
;     ${common.build_flags}
;     -DBREWPI_LCD
;     -DBREWPI_IIC
;     -DCONNECT_VIA_SERIAL
;     ; -DEXTERN_SENSOR_ACTUATOR_SUPPORT
;     -DESP32S2
; lib_deps =
;     ${common.lib_deps}
; upload_speed = ${common.upload_speed}
; monitor_speed = ${common.monitor_speed}
; board_build.embed_txtfiles = ${common.board_build.embed_txtfiles}
; board_build.partitions = 4mb_inc_ota.csv
; board_build.filesystem = littlefs
; build_type = ${common.build_type}
; custom_component_remove = ${common.custom_component_remove}
; monitor_filters =
;     esp32_exception_decoder

[env:esp32_wifi_espi]
board = esp32dev
platform = ${common.platform}
framework = ${common.framework}
; board_build.arduino.upstream_packages = no
; For esp32_wifi_tft we want to enable LCD support, TFT support, and WiFi support
build_flags =
    ${common.build_flags}
    -DBREWPI_LCD
    -DBREWPI_TFT
    -DBREWPI_TFT_ESPI
    -DHAS_AXP192
    -DCONNECT_VIA_WIFI
    -DHAS_BLUETOOTH
    -DEXTERN_SENSOR_ACTUATOR_SUPPORT
    ; -DENABLE_PROMETHEUS_SERVER
    -DENABLE_HTTP_INTERFACE
    -DESP32_STOCK
    -DUSER_SETUP_LOADED=1
    -DST7789_DRIVER=1
    -DTFT_WIDTH=135
    -DTFT_HEIGHT=240
    -DCGRAM_OFFSET=1
    -DTFT_MISO=-1
    -DTFT_MOSI=15
    -DTFT_SCLK=13
    -DTFT_CS=5
    -DTFT_DC=23
    -DTFT_RST=18
    -DLOAD_GFXFF=1
    -DSMOOTH_FONT=1

lib_deps =
    ${common.lib_deps}
    ${common.lib_deps_bluetooth}
    ; bodmer/TFT_eSPI @ 2.5.43 ; https://github.com/Bodmer/TFT_eSPI.git
    https://github.com/Bodmer/TFT_eSPI.git#5793878d24161c1ed23ccb136f8564f332506d53 ; master as of 7/6/24
upload_speed = 1500000
monitor_speed = ${common.monitor_speed}
board_build.embed_txtfiles = ${common.board_build.embed_txtfiles}
board_build.partitions = 4mb_no_ota.csv
board_build.filesystem = littlefs
build_type = ${common.build_type}
custom_sdkconfig = ${common.custom_sdkconfig}
custom_component_remove = ${common.custom_component_remove}
monitor_filters =
    esp32_exception_decoder
